[tool.poetry]
name = "async-websocket-pool"
version = "0.1.3"
description = "async-websocket-pool is a Python library that enables efficient creation and management of a pool of asynchronous WebSocket clients."
authors = ["mpol1t"]
license = "MIT"
readme = "README.md"
packages = [{include = "async_websocket_pool"}]

[tool.poetry.dependencies]
python = "^3.10"
websockets = "^11.0.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pytest-asyncio = "^0.21.0"
coverage = "^7.2.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
